dm-langserver: DMLang.Server.Parser.IDMListener Interface Reference
DMLang.Server.Parser.IDMListener Interface Reference
This interface defines a complete listener for a parse tree produced by DMParser.
Public Member Functions
void EnterLanguage ([NotNull] DMParser.LanguageContext context)
Enter a parse tree produced by DMParser.language.
void ExitLanguage ([NotNull] DMParser.LanguageContext context)
Exit a parse tree produced by DMParser.language.
void EnterDefinition ([NotNull] DMParser.DefinitionContext context)
Enter a parse tree produced by DMParser.definition.
void ExitDefinition ([NotNull] DMParser.DefinitionContext context)
Exit a parse tree produced by DMParser.definition.
void EnterDefinition_type ([NotNull] DMParser.Definition_typeContext context)
Enter a parse tree produced by DMParser.definition_type.
void ExitDefinition_type ([NotNull] DMParser.Definition_typeContext context)
Exit a parse tree produced by DMParser.definition_type.
void EnterOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Enter a parse tree produced by DMParser.optional_slash.
void ExitOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Exit a parse tree produced by DMParser.optional_slash.
void EnterString_text ([NotNull] DMParser.String_textContext context)
Enter a parse tree produced by DMParser.string_text.
void ExitString_text ([NotNull] DMParser.String_textContext context)
Exit a parse tree produced by DMParser.string_text.
void EnterRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Enter a parse tree produced by DMParser.root_var_def.
void ExitRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Exit a parse tree produced by DMParser.root_var_def.
void EnterVar_def ([NotNull] DMParser.Var_defContext context)
Enter a parse tree produced by DMParser.var_def.
void ExitVar_def ([NotNull] DMParser.Var_defContext context)
Exit a parse tree produced by DMParser.var_def.
void EnterId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Enter a parse tree produced by DMParser.id_typepath_decl_block.
void ExitId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Exit a parse tree produced by DMParser.id_typepath_decl_block.
void EnterId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Enter a parse tree produced by DMParser.id_typepath_decl.
void ExitId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Exit a parse tree produced by DMParser.id_typepath_decl.
void EnterVar_qualifier ([NotNull] DMParser.Var_qualifierContext context)
Enter a parse tree produced by DMParser.var_qualifier.
void ExitVar_qualifier ([NotNull] DMParser.Var_qualifierContext context)
Exit a parse tree produced by DMParser.var_qualifier.
void EnterStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Enter a parse tree produced by DMParser.static_or_global.
void ExitStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Exit a parse tree produced by DMParser.static_or_global.
void EnterId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Enter a parse tree produced by DMParser.id_typepath_block.
void ExitId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Exit a parse tree produced by DMParser.id_typepath_block.
void EnterId_typepath ([NotNull] DMParser.Id_typepathContext context)
Enter a parse tree produced by DMParser.id_typepath.
void ExitId_typepath ([NotNull] DMParser.Id_typepathContext context)
Exit a parse tree produced by DMParser.id_typepath.
void EnterCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Enter a parse tree produced by DMParser.custom_id_typepath_block.
void ExitCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Exit a parse tree produced by DMParser.custom_id_typepath_block.
void EnterCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Enter a parse tree produced by DMParser.custom_id_typepath.
void ExitCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Exit a parse tree produced by DMParser.custom_id_typepath.
void EnterId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Enter a parse tree produced by DMParser.id_and_assignment.
void ExitId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Exit a parse tree produced by DMParser.id_and_assignment.
void EnterFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Enter a parse tree produced by DMParser.full_typepath.
void ExitFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Exit a parse tree produced by DMParser.full_typepath.
void EnterTypepath ([NotNull] DMParser.TypepathContext context)
Enter a parse tree produced by DMParser.typepath.
void ExitTypepath ([NotNull] DMParser.TypepathContext context)
Exit a parse tree produced by DMParser.typepath.
void EnterId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Enter a parse tree produced by DMParser.id_typepath_oneline.
void ExitId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Exit a parse tree produced by DMParser.id_typepath_oneline.
void EnterDatum_def ([NotNull] DMParser.Datum_defContext context)
Enter a parse tree produced by DMParser.datum_def.
void ExitDatum_def ([NotNull] DMParser.Datum_defContext context)
Exit a parse tree produced by DMParser.datum_def.
void EnterDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Enter a parse tree produced by DMParser.datum_inner_def.
void ExitDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Exit a parse tree produced by DMParser.datum_inner_def.
void EnterDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Enter a parse tree produced by DMParser.datum_def_block.
void ExitDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Exit a parse tree produced by DMParser.datum_def_block.
void EnterDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Enter a parse tree produced by DMParser.datum_def_contents.
void ExitDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Exit a parse tree produced by DMParser.datum_def_contents.
void EnterProc_def ([NotNull] DMParser.Proc_defContext context)
Enter a parse tree produced by DMParser.proc_def.
void ExitProc_def ([NotNull] DMParser.Proc_defContext context)
Exit a parse tree produced by DMParser.proc_def.
void EnterProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Enter a parse tree produced by DMParser.proc_id_def_block.
void ExitProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Exit a parse tree produced by DMParser.proc_id_def_block.
void EnterProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Enter a parse tree produced by DMParser.proc_id_def.
void ExitProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Exit a parse tree produced by DMParser.proc_id_def.
void EnterArguments_def ([NotNull] DMParser.Arguments_defContext context)
Enter a parse tree produced by DMParser.arguments_def.
void ExitArguments_def ([NotNull] DMParser.Arguments_defContext context)
Exit a parse tree produced by DMParser.arguments_def.
void EnterArgument_def ([NotNull] DMParser.Argument_defContext context)
Enter a parse tree produced by DMParser.argument_def.
void ExitArgument_def ([NotNull] DMParser.Argument_defContext context)
Exit a parse tree produced by DMParser.argument_def.
void EnterArgument_decl ([NotNull] DMParser.Argument_declContext context)
Enter a parse tree produced by DMParser.argument_decl.
void ExitArgument_decl ([NotNull] DMParser.Argument_declContext context)
Exit a parse tree produced by DMParser.argument_decl.
void EnterBlock ([NotNull] DMParser.BlockContext context)
Enter a parse tree produced by DMParser.block.
void ExitBlock ([NotNull] DMParser.BlockContext context)
Exit a parse tree produced by DMParser.block.
void EnterStatements ([NotNull] DMParser.StatementsContext context)
Enter a parse tree produced by DMParser.statements.
void ExitStatements ([NotNull] DMParser.StatementsContext context)
Exit a parse tree produced by DMParser.statements.
void EnterStatement ([NotNull] DMParser.StatementContext context)
Enter a parse tree produced by DMParser.statement.
void ExitStatement ([NotNull] DMParser.StatementContext context)
Exit a parse tree produced by DMParser.statement.
void EnterProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Enter a parse tree produced by DMParser.proccall_statement.
void ExitProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Exit a parse tree produced by DMParser.proccall_statement.
void EnterAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Enter a parse tree produced by DMParser.assignment_statement.
void ExitAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Exit a parse tree produced by DMParser.assignment_statement.
void EnterLabel_statement ([NotNull] DMParser.Label_statementContext context)
Enter a parse tree produced by DMParser.label_statement.
void ExitLabel_statement ([NotNull] DMParser.Label_statementContext context)
Exit a parse tree produced by DMParser.label_statement.
void EnterGoto_statement ([NotNull] DMParser.Goto_statementContext context)
Enter a parse tree produced by DMParser.goto_statement.
void ExitGoto_statement ([NotNull] DMParser.Goto_statementContext context)
Exit a parse tree produced by DMParser.goto_statement.
void EnterThrow_statement ([NotNull] DMParser.Throw_statementContext context)
Enter a parse tree produced by DMParser.throw_statement.
void ExitThrow_statement ([NotNull] DMParser.Throw_statementContext context)
Exit a parse tree produced by DMParser.throw_statement.
void EnterReturn_statement ([NotNull] DMParser.Return_statementContext context)
Enter a parse tree produced by DMParser.return_statement.
void ExitReturn_statement ([NotNull] DMParser.Return_statementContext context)
Exit a parse tree produced by DMParser.return_statement.
void EnterControl_flow ([NotNull] DMParser.Control_flowContext context)
Enter a parse tree produced by DMParser.control_flow.
void ExitControl_flow ([NotNull] DMParser.Control_flowContext context)
Exit a parse tree produced by DMParser.control_flow.
void EnterSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Enter a parse tree produced by DMParser.spawn_statement.
void ExitSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Exit a parse tree produced by DMParser.spawn_statement.
void EnterSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Enter a parse tree produced by DMParser.spawn_invocation.
void ExitSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Exit a parse tree produced by DMParser.spawn_invocation.
void EnterIf_statement ([NotNull] DMParser.If_statementContext context)
Enter a parse tree produced by DMParser.if_statement.
void ExitIf_statement ([NotNull] DMParser.If_statementContext context)
Exit a parse tree produced by DMParser.if_statement.
void EnterRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Enter a parse tree produced by DMParser.root_if_continuation.
void ExitRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Exit a parse tree produced by DMParser.root_if_continuation.
void EnterIf_check ([NotNull] DMParser.If_checkContext context)
Enter a parse tree produced by DMParser.if_check.
void ExitIf_check ([NotNull] DMParser.If_checkContext context)
Exit a parse tree produced by DMParser.if_check.
void EnterIf_continuation ([NotNull] DMParser.If_continuationContext context)
Enter a parse tree produced by DMParser.if_continuation.
void ExitIf_continuation ([NotNull] DMParser.If_continuationContext context)
Exit a parse tree produced by DMParser.if_continuation.
void EnterSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Enter a parse tree produced by DMParser.switch_statement.
void ExitSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Exit a parse tree produced by DMParser.switch_statement.
void EnterConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Enter a parse tree produced by DMParser.const_if_check.
void ExitConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Exit a parse tree produced by DMParser.const_if_check.
void EnterRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Enter a parse tree produced by DMParser.root_switch_block.
void ExitRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Exit a parse tree produced by DMParser.root_switch_block.
void EnterSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Enter a parse tree produced by DMParser.switch_block.
void ExitSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Exit a parse tree produced by DMParser.switch_block.
void EnterWhile_statement ([NotNull] DMParser.While_statementContext context)
Enter a parse tree produced by DMParser.while_statement.
void ExitWhile_statement ([NotNull] DMParser.While_statementContext context)
Exit a parse tree produced by DMParser.while_statement.
void EnterFor_statement ([NotNull] DMParser.For_statementContext context)
Enter a parse tree produced by DMParser.for_statement.
void ExitFor_statement ([NotNull] DMParser.For_statementContext context)
Exit a parse tree produced by DMParser.for_statement.
void EnterFor_expression ([NotNull] DMParser.For_expressionContext context)
Enter a parse tree produced by DMParser.for_expression.
void ExitFor_expression ([NotNull] DMParser.For_expressionContext context)
Exit a parse tree produced by DMParser.for_expression.
void EnterFor_in ([NotNull] DMParser.For_inContext context)
Enter a parse tree produced by DMParser.for_in.
void ExitFor_in ([NotNull] DMParser.For_inContext context)
Exit a parse tree produced by DMParser.for_in.
void EnterFor_standard ([NotNull] DMParser.For_standardContext context)
Enter a parse tree produced by DMParser.for_standard.
void ExitFor_standard ([NotNull] DMParser.For_standardContext context)
Exit a parse tree produced by DMParser.for_standard.
void EnterFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Enter a parse tree produced by DMParser.for_optional_argument_def.
void ExitFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Exit a parse tree produced by DMParser.for_optional_argument_def.
void EnterOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Enter a parse tree produced by DMParser.optional_expression.
void ExitOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Exit a parse tree produced by DMParser.optional_expression.
void EnterProccall ([NotNull] DMParser.ProccallContext context)
Enter a parse tree produced by DMParser.proccall.
void ExitProccall ([NotNull] DMParser.ProccallContext context)
Exit a parse tree produced by DMParser.proccall.
void EnterProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Enter a parse tree produced by DMParser.proc_invocation.
void ExitProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Exit a parse tree produced by DMParser.proc_invocation.
void EnterProc_arguments ([NotNull] DMParser.Proc_argumentsContext context)
Enter a parse tree produced by DMParser.proc_arguments.
void ExitProc_arguments ([NotNull] DMParser.Proc_argumentsContext context)
Exit a parse tree produced by DMParser.proc_arguments.
void EnterUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Enter a parse tree produced by DMParser.unquotable_associated_argument.
void ExitUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Exit a parse tree produced by DMParser.unquotable_associated_argument.
void EnterArguments ([NotNull] DMParser.ArgumentsContext context)
Enter a parse tree produced by DMParser.arguments.
void ExitArguments ([NotNull] DMParser.ArgumentsContext context)
Exit a parse tree produced by DMParser.arguments.
void EnterAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Enter a parse tree produced by DMParser.associated_argument.
void ExitAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Exit a parse tree produced by DMParser.associated_argument.
void EnterAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Enter a parse tree produced by DMParser.associated_arguments.
void ExitAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Exit a parse tree produced by DMParser.associated_arguments.
void EnterList_declaration ([NotNull] DMParser.List_declarationContext context)
Enter a parse tree produced by DMParser.list_declaration.
void ExitList_declaration ([NotNull] DMParser.List_declarationContext context)
Exit a parse tree produced by DMParser.list_declaration.
void EnterId_specifier ([NotNull] DMParser.Id_specifierContext context)
Enter a parse tree produced by DMParser.id_specifier.
void ExitId_specifier ([NotNull] DMParser.Id_specifierContext context)
Exit a parse tree produced by DMParser.id_specifier.
void EnterInner_id_specifier ([NotNull] DMParser.Inner_id_specifierContext context)
Enter a parse tree produced by DMParser.inner_id_specifier.
void ExitInner_id_specifier ([NotNull] DMParser.Inner_id_specifierContext context)
Exit a parse tree produced by DMParser.inner_id_specifier.
void EnterDatum_access ([NotNull] DMParser.Datum_accessContext context)
Enter a parse tree produced by DMParser.datum_access.
void ExitDatum_access ([NotNull] DMParser.Datum_accessContext context)
Exit a parse tree produced by DMParser.datum_access.
void EnterExpression ([NotNull] DMParser.ExpressionContext context)
Enter a parse tree produced by DMParser.expression.
void ExitExpression ([NotNull] DMParser.ExpressionContext context)
Exit a parse tree produced by DMParser.expression.
void EnterWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Enter a parse tree produced by DMParser.wrapped_expression.
void ExitWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Exit a parse tree produced by DMParser.wrapped_expression.
void EnterInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Enter a parse tree produced by DMParser.inner_expression.
void ExitInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Exit a parse tree produced by DMParser.inner_expression.
void EnterNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_expression.
void ExitNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_expression.
void EnterNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_wrapped_expression.
void ExitNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_wrapped_expression.
void EnterNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_inner_expression.
void ExitNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_inner_expression.
void EnterList_access ([NotNull] DMParser.List_accessContext context)
Enter a parse tree produced by DMParser.list_access.
void ExitList_access ([NotNull] DMParser.List_accessContext context)
Exit a parse tree produced by DMParser.list_access.
void EnterOperation ([NotNull] DMParser.OperationContext context)
Enter a parse tree produced by DMParser.operation.
void ExitOperation ([NotNull] DMParser.OperationContext context)
Exit a parse tree produced by DMParser.operation.
void EnterValue_range ([NotNull] DMParser.Value_rangeContext context)
Enter a parse tree produced by DMParser.value_range.
void ExitValue_range ([NotNull] DMParser.Value_rangeContext context)
Exit a parse tree produced by DMParser.value_range.
void EnterTernery ([NotNull] DMParser.TerneryContext context)
Enter a parse tree produced by DMParser.ternery.
void ExitTernery ([NotNull] DMParser.TerneryContext context)
Exit a parse tree produced by DMParser.ternery.
void EnterLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Enter a parse tree produced by DMParser.lhrh_op.
void ExitLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Exit a parse tree produced by DMParser.lhrh_op.
void EnterValue ([NotNull] DMParser.ValueContext context)
Enter a parse tree produced by DMParser.value.
void ExitValue ([NotNull] DMParser.ValueContext context)
Exit a parse tree produced by DMParser.value.
void EnterConstexpr ([NotNull] DMParser.ConstexprContext context)
Enter a parse tree produced by DMParser.constexpr.
void ExitConstexpr ([NotNull] DMParser.ConstexprContext context)
Exit a parse tree produced by DMParser.constexpr.
void EnterProctype ([NotNull] DMParser.ProctypeContext context)
Enter a parse tree produced by DMParser.proctype.
void ExitProctype ([NotNull] DMParser.ProctypeContext context)
Exit a parse tree produced by DMParser.proctype.
void EnterAssignment ([NotNull] DMParser.AssignmentContext context)
Enter a parse tree produced by DMParser.assignment.
void ExitAssignment ([NotNull] DMParser.AssignmentContext context)
Exit a parse tree produced by DMParser.assignment.
void EnterAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Enter a parse tree produced by DMParser.assignment_op.
void ExitAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Exit a parse tree produced by DMParser.assignment_op.
void EnterEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Enter a parse tree produced by DMParser.embedded_expression.
void ExitEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Exit a parse tree produced by DMParser.embedded_expression.
void EnterInner_string ([NotNull] DMParser.Inner_stringContext context)
Enter a parse tree produced by DMParser.inner_string.
void ExitInner_string ([NotNull] DMParser.Inner_stringContext context)
Exit a parse tree produced by DMParser.inner_string.
void EnterInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Enter a parse tree produced by DMParser.inner_string_entry.
void ExitInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Exit a parse tree produced by DMParser.inner_string_entry.
void EnterString_entry ([NotNull] DMParser.String_entryContext context)
Enter a parse tree produced by DMParser.string_entry.
void ExitString_entry ([NotNull] DMParser.String_entryContext context)
Exit a parse tree produced by DMParser.string_entry.
void EnterFile_ref ([NotNull] DMParser.File_refContext context)
Enter a parse tree produced by DMParser.file_ref.
void ExitFile_ref ([NotNull] DMParser.File_refContext context)
Exit a parse tree produced by DMParser.file_ref.
void EnterNumber ([NotNull] DMParser.NumberContext context)
Enter a parse tree produced by DMParser.number.
void ExitNumber ([NotNull] DMParser.NumberContext context)
Exit a parse tree produced by DMParser.number.
void EnterEquals ([NotNull] DMParser.EqualsContext context)
Enter a parse tree produced by DMParser.equals.
void ExitEquals ([NotNull] DMParser.EqualsContext context)
Exit a parse tree produced by DMParser.equals.
void EnterNot_equals ([NotNull] DMParser.Not_equalsContext context)
Enter a parse tree produced by DMParser.not_equals.
void ExitNot_equals ([NotNull] DMParser.Not_equalsContext context)
Exit a parse tree produced by DMParser.not_equals.
void EnterAnd ([NotNull] DMParser.AndContext context)
Enter a parse tree produced by DMParser.and.
void ExitAnd ([NotNull] DMParser.AndContext context)
Exit a parse tree produced by DMParser.and.
void EnterOr ([NotNull] DMParser.OrContext context)
Enter a parse tree produced by DMParser.or.
void ExitOr ([NotNull] DMParser.OrContext context)
Exit a parse tree produced by DMParser.or.
void EnterPow ([NotNull] DMParser.PowContext context)
Enter a parse tree produced by DMParser.pow.
void ExitPow ([NotNull] DMParser.PowContext context)
Exit a parse tree produced by DMParser.pow.
void EnterOr_equals ([NotNull] DMParser.Or_equalsContext context)
Enter a parse tree produced by DMParser.or_equals.
void ExitOr_equals ([NotNull] DMParser.Or_equalsContext context)
Exit a parse tree produced by DMParser.or_equals.
void EnterAnd_equals ([NotNull] DMParser.And_equalsContext context)
Enter a parse tree produced by DMParser.and_equals.
void ExitAnd_equals ([NotNull] DMParser.And_equalsContext context)
Exit a parse tree produced by DMParser.and_equals.
void EnterXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Enter a parse tree produced by DMParser.xor_equals.
void ExitXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Exit a parse tree produced by DMParser.xor_equals.
void EnterMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Enter a parse tree produced by DMParser.mult_equals.
void ExitMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Exit a parse tree produced by DMParser.mult_equals.
void EnterMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Enter a parse tree produced by DMParser.minus_equals.
void ExitMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Exit a parse tree produced by DMParser.minus_equals.
void EnterPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Enter a parse tree produced by DMParser.plus_equals.
void ExitPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Exit a parse tree produced by DMParser.plus_equals.
void EnterSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Enter a parse tree produced by DMParser.slash_equals.
void ExitSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Exit a parse tree produced by DMParser.slash_equals.
void EnterRoot_type ([NotNull] DMParser.Root_typeContext context)
Enter a parse tree produced by DMParser.root_type.
void ExitRoot_type ([NotNull] DMParser.Root_typeContext context)
Exit a parse tree produced by DMParser.root_type.
Detailed Description
This interface defines a complete listener for a parse tree produced by DMParser.
Definition at line 33 of file DMListener.cs.
Member Function Documentation
void DMLang.Server.Parser.IDMListener.EnterAnd ([NotNull] DMParser.AndContext context)
Enter a parse tree produced by DMParser.and.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.AndContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAnd_equals ([NotNull] DMParser.And_equalsContext context)
Enter a parse tree produced by DMParser.and_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.And_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterArgument_decl ([NotNull] DMParser.Argument_declContext context)
Enter a parse tree produced by DMParser.argument_decl.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Argument_declContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterArgument_def ([NotNull] DMParser.Argument_defContext context)
Enter a parse tree produced by DMParser.argument_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Argument_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterArguments ([NotNull] DMParser.ArgumentsContext context)
Enter a parse tree produced by DMParser.arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ArgumentsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterArguments_def ([NotNull] DMParser.Arguments_defContext context)
Enter a parse tree produced by DMParser.arguments_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Arguments_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAssignment ([NotNull] DMParser.AssignmentContext context)
Enter a parse tree produced by DMParser.assignment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.AssignmentContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Enter a parse tree produced by DMParser.assignment_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Assignment_opContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Enter a parse tree produced by DMParser.assignment_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Assignment_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Enter a parse tree produced by DMParser.associated_argument.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Associated_argumentContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Enter a parse tree produced by DMParser.associated_arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Associated_argumentsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterBlock ([NotNull] DMParser.BlockContext context)
Enter a parse tree produced by DMParser.block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.BlockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Enter a parse tree produced by DMParser.const_if_check.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Const_if_checkContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterConstexpr ([NotNull] DMParser.ConstexprContext context)
Enter a parse tree produced by DMParser.constexpr.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ConstexprContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterControl_flow ([NotNull] DMParser.Control_flowContext context)
Enter a parse tree produced by DMParser.control_flow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Control_flowContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Enter a parse tree produced by DMParser.custom_id_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Custom_id_typepathContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Enter a parse tree produced by DMParser.custom_id_typepath_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Custom_id_typepath_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDatum_access ([NotNull] DMParser.Datum_accessContext context)
Enter a parse tree produced by DMParser.datum_access.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_accessContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDatum_def ([NotNull] DMParser.Datum_defContext context)
Enter a parse tree produced by DMParser.datum_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Enter a parse tree produced by DMParser.datum_def_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_def_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Enter a parse tree produced by DMParser.datum_def_contents.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_def_contentsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Enter a parse tree produced by DMParser.datum_inner_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_inner_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDefinition ([NotNull] DMParser.DefinitionContext context)
Enter a parse tree produced by DMParser.definition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.DefinitionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterDefinition_type ([NotNull] DMParser.Definition_typeContext context)
Enter a parse tree produced by DMParser.definition_type.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Definition_typeContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Enter a parse tree produced by DMParser.embedded_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Embedded_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterEquals ([NotNull] DMParser.EqualsContext context)
Enter a parse tree produced by DMParser.equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.EqualsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterExpression ([NotNull] DMParser.ExpressionContext context)
Enter a parse tree produced by DMParser.expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ExpressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFile_ref ([NotNull] DMParser.File_refContext context)
Enter a parse tree produced by DMParser.file_ref.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.File_refContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFor_expression ([NotNull] DMParser.For_expressionContext context)
Enter a parse tree produced by DMParser.for_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFor_in ([NotNull] DMParser.For_inContext context)
Enter a parse tree produced by DMParser.for_in.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_inContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Enter a parse tree produced by DMParser.for_optional_argument_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_optional_argument_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFor_standard ([NotNull] DMParser.For_standardContext context)
Enter a parse tree produced by DMParser.for_standard.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_standardContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFor_statement ([NotNull] DMParser.For_statementContext context)
Enter a parse tree produced by DMParser.for_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Enter a parse tree produced by DMParser.full_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Full_typepathContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterGoto_statement ([NotNull] DMParser.Goto_statementContext context)
Enter a parse tree produced by DMParser.goto_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Goto_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Enter a parse tree produced by DMParser.id_and_assignment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_and_assignmentContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_specifier ([NotNull] DMParser.Id_specifierContext context)
Enter a parse tree produced by DMParser.id_specifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_specifierContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_typepath ([NotNull] DMParser.Id_typepathContext context)
Enter a parse tree produced by DMParser.id_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepathContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Enter a parse tree produced by DMParser.id_typepath_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Enter a parse tree produced by DMParser.id_typepath_decl.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_declContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Enter a parse tree produced by DMParser.id_typepath_decl_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_decl_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Enter a parse tree produced by DMParser.id_typepath_oneline.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_onelineContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterIf_check ([NotNull] DMParser.If_checkContext context)
Enter a parse tree produced by DMParser.if_check.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_checkContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterIf_continuation ([NotNull] DMParser.If_continuationContext context)
Enter a parse tree produced by DMParser.if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_continuationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterIf_statement ([NotNull] DMParser.If_statementContext context)
Enter a parse tree produced by DMParser.if_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Enter a parse tree produced by DMParser.inner_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterInner_id_specifier ([NotNull] DMParser.Inner_id_specifierContext context)
Enter a parse tree produced by DMParser.inner_id_specifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_id_specifierContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterInner_string ([NotNull] DMParser.Inner_stringContext context)
Enter a parse tree produced by DMParser.inner_string.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_stringContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Enter a parse tree produced by DMParser.inner_string_entry.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_string_entryContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterLabel_statement ([NotNull] DMParser.Label_statementContext context)
Enter a parse tree produced by DMParser.label_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Label_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterLanguage ([NotNull] DMParser.LanguageContext context)
Enter a parse tree produced by DMParser.language.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.LanguageContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Enter a parse tree produced by DMParser.lhrh_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Lhrh_opContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterList_access ([NotNull] DMParser.List_accessContext context)
Enter a parse tree produced by DMParser.list_access.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.List_accessContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterList_declaration ([NotNull] DMParser.List_declarationContext context)
Enter a parse tree produced by DMParser.list_declaration.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.List_declarationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Enter a parse tree produced by DMParser.minus_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Minus_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Enter a parse tree produced by DMParser.mult_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Mult_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_inner_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_inner_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Enter a parse tree produced by DMParser.non_recursive_wrapped_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_wrapped_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterNot_equals ([NotNull] DMParser.Not_equalsContext context)
Enter a parse tree produced by DMParser.not_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Not_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterNumber ([NotNull] DMParser.NumberContext context)
Enter a parse tree produced by DMParser.number.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.NumberContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterOperation ([NotNull] DMParser.OperationContext context)
Enter a parse tree produced by DMParser.operation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.OperationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Enter a parse tree produced by DMParser.optional_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Optional_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Enter a parse tree produced by DMParser.optional_slash.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Optional_slashContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterOr ([NotNull] DMParser.OrContext context)
Enter a parse tree produced by DMParser.or.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.OrContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterOr_equals ([NotNull] DMParser.Or_equalsContext context)
Enter a parse tree produced by DMParser.or_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Or_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Enter a parse tree produced by DMParser.plus_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Plus_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterPow ([NotNull] DMParser.PowContext context)
Enter a parse tree produced by DMParser.pow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.PowContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProc_arguments ([NotNull] DMParser.Proc_argumentsContext context)
Enter a parse tree produced by DMParser.proc_arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_argumentsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProc_def ([NotNull] DMParser.Proc_defContext context)
Enter a parse tree produced by DMParser.proc_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Enter a parse tree produced by DMParser.proc_id_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_id_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Enter a parse tree produced by DMParser.proc_id_def_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_id_def_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Enter a parse tree produced by DMParser.proc_invocation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_invocationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProccall ([NotNull] DMParser.ProccallContext context)
Enter a parse tree produced by DMParser.proccall.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ProccallContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Enter a parse tree produced by DMParser.proccall_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proccall_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterProctype ([NotNull] DMParser.ProctypeContext context)
Enter a parse tree produced by DMParser.proctype.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ProctypeContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterReturn_statement ([NotNull] DMParser.Return_statementContext context)
Enter a parse tree produced by DMParser.return_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Return_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Enter a parse tree produced by DMParser.root_if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_if_continuationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Enter a parse tree produced by DMParser.root_switch_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_switch_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterRoot_type ([NotNull] DMParser.Root_typeContext context)
Enter a parse tree produced by DMParser.root_type.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_typeContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Enter a parse tree produced by DMParser.root_var_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_var_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Enter a parse tree produced by DMParser.slash_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Slash_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Enter a parse tree produced by DMParser.spawn_invocation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Spawn_invocationContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Enter a parse tree produced by DMParser.spawn_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Spawn_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterStatement ([NotNull] DMParser.StatementContext context)
Enter a parse tree produced by DMParser.statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.StatementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterStatements ([NotNull] DMParser.StatementsContext context)
Enter a parse tree produced by DMParser.statements.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.StatementsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Enter a parse tree produced by DMParser.static_or_global.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Static_or_globalContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterString_entry ([NotNull] DMParser.String_entryContext context)
Enter a parse tree produced by DMParser.string_entry.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.String_entryContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterString_text ([NotNull] DMParser.String_textContext context)
Enter a parse tree produced by DMParser.string_text.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.String_textContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Enter a parse tree produced by DMParser.switch_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Switch_blockContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Enter a parse tree produced by DMParser.switch_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Switch_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterTernery ([NotNull] DMParser.TerneryContext context)
Enter a parse tree produced by DMParser.ternery.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.TerneryContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterThrow_statement ([NotNull] DMParser.Throw_statementContext context)
Enter a parse tree produced by DMParser.throw_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Throw_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterTypepath ([NotNull] DMParser.TypepathContext context)
Enter a parse tree produced by DMParser.typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.TypepathContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Enter a parse tree produced by DMParser.unquotable_associated_argument.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Unquotable_associated_argumentContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterValue ([NotNull] DMParser.ValueContext context)
Enter a parse tree produced by DMParser.value.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ValueContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterValue_range ([NotNull] DMParser.Value_rangeContext context)
Enter a parse tree produced by DMParser.value_range.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Value_rangeContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterVar_def ([NotNull] DMParser.Var_defContext context)
Enter a parse tree produced by DMParser.var_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Var_defContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterVar_qualifier ([NotNull] DMParser.Var_qualifierContext context)
Enter a parse tree produced by DMParser.var_qualifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Var_qualifierContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterWhile_statement ([NotNull] DMParser.While_statementContext context)
Enter a parse tree produced by DMParser.while_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.While_statementContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Enter a parse tree produced by DMParser.wrapped_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Wrapped_expressionContext.EnterRule().
void DMLang.Server.Parser.IDMListener.EnterXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Enter a parse tree produced by DMParser.xor_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Xor_equalsContext.EnterRule().
void DMLang.Server.Parser.IDMListener.ExitAnd ([NotNull] DMParser.AndContext context)
Exit a parse tree produced by DMParser.and.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.AndContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAnd_equals ([NotNull] DMParser.And_equalsContext context)
Exit a parse tree produced by DMParser.and_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.And_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitArgument_decl ([NotNull] DMParser.Argument_declContext context)
Exit a parse tree produced by DMParser.argument_decl.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Argument_declContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitArgument_def ([NotNull] DMParser.Argument_defContext context)
Exit a parse tree produced by DMParser.argument_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Argument_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitArguments ([NotNull] DMParser.ArgumentsContext context)
Exit a parse tree produced by DMParser.arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ArgumentsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitArguments_def ([NotNull] DMParser.Arguments_defContext context)
Exit a parse tree produced by DMParser.arguments_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Arguments_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAssignment ([NotNull] DMParser.AssignmentContext context)
Exit a parse tree produced by DMParser.assignment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.AssignmentContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Exit a parse tree produced by DMParser.assignment_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Assignment_opContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Exit a parse tree produced by DMParser.assignment_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Assignment_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Exit a parse tree produced by DMParser.associated_argument.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Associated_argumentContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Exit a parse tree produced by DMParser.associated_arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Associated_argumentsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitBlock ([NotNull] DMParser.BlockContext context)
Exit a parse tree produced by DMParser.block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.BlockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Exit a parse tree produced by DMParser.const_if_check.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Const_if_checkContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitConstexpr ([NotNull] DMParser.ConstexprContext context)
Exit a parse tree produced by DMParser.constexpr.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ConstexprContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitControl_flow ([NotNull] DMParser.Control_flowContext context)
Exit a parse tree produced by DMParser.control_flow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Control_flowContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Exit a parse tree produced by DMParser.custom_id_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Custom_id_typepathContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Exit a parse tree produced by DMParser.custom_id_typepath_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Custom_id_typepath_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDatum_access ([NotNull] DMParser.Datum_accessContext context)
Exit a parse tree produced by DMParser.datum_access.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_accessContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDatum_def ([NotNull] DMParser.Datum_defContext context)
Exit a parse tree produced by DMParser.datum_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Exit a parse tree produced by DMParser.datum_def_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_def_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Exit a parse tree produced by DMParser.datum_def_contents.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_def_contentsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Exit a parse tree produced by DMParser.datum_inner_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Datum_inner_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDefinition ([NotNull] DMParser.DefinitionContext context)
Exit a parse tree produced by DMParser.definition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.DefinitionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitDefinition_type ([NotNull] DMParser.Definition_typeContext context)
Exit a parse tree produced by DMParser.definition_type.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Definition_typeContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Exit a parse tree produced by DMParser.embedded_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Embedded_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitEquals ([NotNull] DMParser.EqualsContext context)
Exit a parse tree produced by DMParser.equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.EqualsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitExpression ([NotNull] DMParser.ExpressionContext context)
Exit a parse tree produced by DMParser.expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ExpressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFile_ref ([NotNull] DMParser.File_refContext context)
Exit a parse tree produced by DMParser.file_ref.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.File_refContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFor_expression ([NotNull] DMParser.For_expressionContext context)
Exit a parse tree produced by DMParser.for_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFor_in ([NotNull] DMParser.For_inContext context)
Exit a parse tree produced by DMParser.for_in.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_inContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Exit a parse tree produced by DMParser.for_optional_argument_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_optional_argument_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFor_standard ([NotNull] DMParser.For_standardContext context)
Exit a parse tree produced by DMParser.for_standard.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_standardContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFor_statement ([NotNull] DMParser.For_statementContext context)
Exit a parse tree produced by DMParser.for_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.For_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Exit a parse tree produced by DMParser.full_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Full_typepathContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitGoto_statement ([NotNull] DMParser.Goto_statementContext context)
Exit a parse tree produced by DMParser.goto_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Goto_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Exit a parse tree produced by DMParser.id_and_assignment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_and_assignmentContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_specifier ([NotNull] DMParser.Id_specifierContext context)
Exit a parse tree produced by DMParser.id_specifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_specifierContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_typepath ([NotNull] DMParser.Id_typepathContext context)
Exit a parse tree produced by DMParser.id_typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepathContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Exit a parse tree produced by DMParser.id_typepath_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Exit a parse tree produced by DMParser.id_typepath_decl.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_declContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Exit a parse tree produced by DMParser.id_typepath_decl_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_decl_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Exit a parse tree produced by DMParser.id_typepath_oneline.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Id_typepath_onelineContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitIf_check ([NotNull] DMParser.If_checkContext context)
Exit a parse tree produced by DMParser.if_check.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_checkContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitIf_continuation ([NotNull] DMParser.If_continuationContext context)
Exit a parse tree produced by DMParser.if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_continuationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitIf_statement ([NotNull] DMParser.If_statementContext context)
Exit a parse tree produced by DMParser.if_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.If_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Exit a parse tree produced by DMParser.inner_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitInner_id_specifier ([NotNull] DMParser.Inner_id_specifierContext context)
Exit a parse tree produced by DMParser.inner_id_specifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_id_specifierContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitInner_string ([NotNull] DMParser.Inner_stringContext context)
Exit a parse tree produced by DMParser.inner_string.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_stringContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Exit a parse tree produced by DMParser.inner_string_entry.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Inner_string_entryContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitLabel_statement ([NotNull] DMParser.Label_statementContext context)
Exit a parse tree produced by DMParser.label_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Label_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitLanguage ([NotNull] DMParser.LanguageContext context)
Exit a parse tree produced by DMParser.language.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.LanguageContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Exit a parse tree produced by DMParser.lhrh_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Lhrh_opContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitList_access ([NotNull] DMParser.List_accessContext context)
Exit a parse tree produced by DMParser.list_access.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.List_accessContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitList_declaration ([NotNull] DMParser.List_declarationContext context)
Exit a parse tree produced by DMParser.list_declaration.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.List_declarationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Exit a parse tree produced by DMParser.minus_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Minus_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Exit a parse tree produced by DMParser.mult_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Mult_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_inner_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_inner_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Exit a parse tree produced by DMParser.non_recursive_wrapped_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Non_recursive_wrapped_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitNot_equals ([NotNull] DMParser.Not_equalsContext context)
Exit a parse tree produced by DMParser.not_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Not_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitNumber ([NotNull] DMParser.NumberContext context)
Exit a parse tree produced by DMParser.number.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.NumberContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitOperation ([NotNull] DMParser.OperationContext context)
Exit a parse tree produced by DMParser.operation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.OperationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Exit a parse tree produced by DMParser.optional_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Optional_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Exit a parse tree produced by DMParser.optional_slash.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Optional_slashContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitOr ([NotNull] DMParser.OrContext context)
Exit a parse tree produced by DMParser.or.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.OrContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitOr_equals ([NotNull] DMParser.Or_equalsContext context)
Exit a parse tree produced by DMParser.or_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Or_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Exit a parse tree produced by DMParser.plus_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Plus_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitPow ([NotNull] DMParser.PowContext context)
Exit a parse tree produced by DMParser.pow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.PowContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProc_arguments ([NotNull] DMParser.Proc_argumentsContext context)
Exit a parse tree produced by DMParser.proc_arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_argumentsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProc_def ([NotNull] DMParser.Proc_defContext context)
Exit a parse tree produced by DMParser.proc_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Exit a parse tree produced by DMParser.proc_id_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_id_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Exit a parse tree produced by DMParser.proc_id_def_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_id_def_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Exit a parse tree produced by DMParser.proc_invocation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proc_invocationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProccall ([NotNull] DMParser.ProccallContext context)
Exit a parse tree produced by DMParser.proccall.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ProccallContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Exit a parse tree produced by DMParser.proccall_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Proccall_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitProctype ([NotNull] DMParser.ProctypeContext context)
Exit a parse tree produced by DMParser.proctype.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ProctypeContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitReturn_statement ([NotNull] DMParser.Return_statementContext context)
Exit a parse tree produced by DMParser.return_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Return_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Exit a parse tree produced by DMParser.root_if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_if_continuationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Exit a parse tree produced by DMParser.root_switch_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_switch_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitRoot_type ([NotNull] DMParser.Root_typeContext context)
Exit a parse tree produced by DMParser.root_type.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_typeContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Exit a parse tree produced by DMParser.root_var_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Root_var_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Exit a parse tree produced by DMParser.slash_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Slash_equalsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Exit a parse tree produced by DMParser.spawn_invocation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Spawn_invocationContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Exit a parse tree produced by DMParser.spawn_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Spawn_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitStatement ([NotNull] DMParser.StatementContext context)
Exit a parse tree produced by DMParser.statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.StatementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitStatements ([NotNull] DMParser.StatementsContext context)
Exit a parse tree produced by DMParser.statements.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.StatementsContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Exit a parse tree produced by DMParser.static_or_global.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Static_or_globalContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitString_entry ([NotNull] DMParser.String_entryContext context)
Exit a parse tree produced by DMParser.string_entry.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.String_entryContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitString_text ([NotNull] DMParser.String_textContext context)
Exit a parse tree produced by DMParser.string_text.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.String_textContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Exit a parse tree produced by DMParser.switch_block.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Switch_blockContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Exit a parse tree produced by DMParser.switch_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Switch_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitTernery ([NotNull] DMParser.TerneryContext context)
Exit a parse tree produced by DMParser.ternery.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.TerneryContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitThrow_statement ([NotNull] DMParser.Throw_statementContext context)
Exit a parse tree produced by DMParser.throw_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Throw_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitTypepath ([NotNull] DMParser.TypepathContext context)
Exit a parse tree produced by DMParser.typepath.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.TypepathContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Exit a parse tree produced by DMParser.unquotable_associated_argument.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Unquotable_associated_argumentContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitValue ([NotNull] DMParser.ValueContext context)
Exit a parse tree produced by DMParser.value.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.ValueContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitValue_range ([NotNull] DMParser.Value_rangeContext context)
Exit a parse tree produced by DMParser.value_range.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Value_rangeContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitVar_def ([NotNull] DMParser.Var_defContext context)
Exit a parse tree produced by DMParser.var_def.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Var_defContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitVar_qualifier ([NotNull] DMParser.Var_qualifierContext context)
Exit a parse tree produced by DMParser.var_qualifier.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Var_qualifierContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitWhile_statement ([NotNull] DMParser.While_statementContext context)
Exit a parse tree produced by DMParser.while_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.While_statementContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Exit a parse tree produced by DMParser.wrapped_expression.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Wrapped_expressionContext.ExitRule().
void DMLang.Server.Parser.IDMListener.ExitXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Exit a parse tree produced by DMParser.xor_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.DMBaseListener.
Referenced by DMLang.Server.Parser.DMParser.Xor_equalsContext.ExitRule().
The documentation for this interface was generated from the following file:
DMLang.Server/obj/Release/DMListener.cs