dm-langserver: Dangl.Calculator.Generated.IDMVisitor< Result > Interface Template Reference
Dangl.Calculator.Generated.IDMVisitor< Result > Interface Template Reference
This interface defines a complete generic visitor for a parse tree produced by DMParser.
Public Member Functions
Result VisitLanguage ([NotNull] DMParser.LanguageContext context)
Visit a parse tree produced by DMParser.language.
Result VisitDefinition ([NotNull] DMParser.DefinitionContext context)
Visit a parse tree produced by DMParser.definition.
Result VisitOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Visit a parse tree produced by DMParser.optional_slash.
Result VisitString_text ([NotNull] DMParser.String_textContext context)
Visit a parse tree produced by DMParser.string_text.
Result VisitRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Visit a parse tree produced by DMParser.root_var_def.
Result VisitVar_def ([NotNull] DMParser.Var_defContext context)
Visit a parse tree produced by DMParser.var_def.
Result VisitId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Visit a parse tree produced by DMParser.id_typepath_decl_block.
Result VisitId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Visit a parse tree produced by DMParser.id_typepath_decl.
Result VisitStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Visit a parse tree produced by DMParser.static_or_global.
Result VisitId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Visit a parse tree produced by DMParser.id_typepath_block.
Result VisitId_typepath ([NotNull] DMParser.Id_typepathContext context)
Visit a parse tree produced by DMParser.id_typepath.
Result VisitCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Visit a parse tree produced by DMParser.custom_id_typepath_block.
Result VisitCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Visit a parse tree produced by DMParser.custom_id_typepath.
Result VisitId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Visit a parse tree produced by DMParser.id_and_assignment.
Result VisitFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Visit a parse tree produced by DMParser.full_typepath.
Result VisitTypepath ([NotNull] DMParser.TypepathContext context)
Visit a parse tree produced by DMParser.typepath.
Result VisitId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Visit a parse tree produced by DMParser.id_typepath_oneline.
Result VisitDatum_def ([NotNull] DMParser.Datum_defContext context)
Visit a parse tree produced by DMParser.datum_def.
Result VisitDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Visit a parse tree produced by DMParser.datum_inner_def.
Result VisitDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Visit a parse tree produced by DMParser.datum_def_block.
Result VisitDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Visit a parse tree produced by DMParser.datum_def_contents.
Result VisitProc_def ([NotNull] DMParser.Proc_defContext context)
Visit a parse tree produced by DMParser.proc_def.
Result VisitProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Visit a parse tree produced by DMParser.proc_id_def_block.
Result VisitProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Visit a parse tree produced by DMParser.proc_id_def.
Result VisitArguments_def ([NotNull] DMParser.Arguments_defContext context)
Visit a parse tree produced by DMParser.arguments_def.
Result VisitArgument_def ([NotNull] DMParser.Argument_defContext context)
Visit a parse tree produced by DMParser.argument_def.
Result VisitArgument_decl ([NotNull] DMParser.Argument_declContext context)
Visit a parse tree produced by DMParser.argument_decl.
Result VisitBlock ([NotNull] DMParser.BlockContext context)
Visit a parse tree produced by DMParser.block.
Result VisitStatements ([NotNull] DMParser.StatementsContext context)
Visit a parse tree produced by DMParser.statements.
Result VisitStatement ([NotNull] DMParser.StatementContext context)
Visit a parse tree produced by DMParser.statement.
Result VisitProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Visit a parse tree produced by DMParser.proccall_statement.
Result VisitAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Visit a parse tree produced by DMParser.assignment_statement.
Result VisitControl_flow ([NotNull] DMParser.Control_flowContext context)
Visit a parse tree produced by DMParser.control_flow.
Result VisitSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Visit a parse tree produced by DMParser.spawn_statement.
Result VisitSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Visit a parse tree produced by DMParser.spawn_invocation.
Result VisitIf_statement ([NotNull] DMParser.If_statementContext context)
Visit a parse tree produced by DMParser.if_statement.
Result VisitRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Visit a parse tree produced by DMParser.root_if_continuation.
Result VisitIf_check ([NotNull] DMParser.If_checkContext context)
Visit a parse tree produced by DMParser.if_check.
Result VisitIf_continuation ([NotNull] DMParser.If_continuationContext context)
Visit a parse tree produced by DMParser.if_continuation.
Result VisitSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Visit a parse tree produced by DMParser.switch_statement.
Result VisitConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Visit a parse tree produced by DMParser.const_if_check.
Result VisitRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Visit a parse tree produced by DMParser.root_switch_block.
Result VisitSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Visit a parse tree produced by DMParser.switch_block.
Result VisitWhile_statement ([NotNull] DMParser.While_statementContext context)
Visit a parse tree produced by DMParser.while_statement.
Result VisitFor_statement ([NotNull] DMParser.For_statementContext context)
Visit a parse tree produced by DMParser.for_statement.
Result VisitFor_expression ([NotNull] DMParser.For_expressionContext context)
Visit a parse tree produced by DMParser.for_expression.
Result VisitFor_in ([NotNull] DMParser.For_inContext context)
Visit a parse tree produced by DMParser.for_in.
Result VisitFor_standard ([NotNull] DMParser.For_standardContext context)
Visit a parse tree produced by DMParser.for_standard.
Result VisitFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Visit a parse tree produced by DMParser.for_optional_argument_def.
Result VisitOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Visit a parse tree produced by DMParser.optional_expression.
Result VisitProccall ([NotNull] DMParser.ProccallContext context)
Visit a parse tree produced by DMParser.proccall.
Result VisitProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Visit a parse tree produced by DMParser.proc_invocation.
Result VisitUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Visit a parse tree produced by DMParser.unquotable_associated_argument.
Result VisitArguments ([NotNull] DMParser.ArgumentsContext context)
Visit a parse tree produced by DMParser.arguments.
Result VisitAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Visit a parse tree produced by DMParser.associated_argument.
Result VisitAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Visit a parse tree produced by DMParser.associated_arguments.
Result VisitList_declaration ([NotNull] DMParser.List_declarationContext context)
Visit a parse tree produced by DMParser.list_declaration.
Result VisitId_specifier ([NotNull] DMParser.Id_specifierContext context)
Visit a parse tree produced by DMParser.id_specifier.
Result VisitDatum_access ([NotNull] DMParser.Datum_accessContext context)
Visit a parse tree produced by DMParser.datum_access.
Result VisitExpression ([NotNull] DMParser.ExpressionContext context)
Visit a parse tree produced by DMParser.expression.
Result VisitWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Visit a parse tree produced by DMParser.wrapped_expression.
Result VisitInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Visit a parse tree produced by DMParser.inner_expression.
Result VisitNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_expression.
Result VisitNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_wrapped_expression.
Result VisitNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_inner_expression.
Result VisitOperation ([NotNull] DMParser.OperationContext context)
Visit a parse tree produced by DMParser.operation.
Result VisitValue_range ([NotNull] DMParser.Value_rangeContext context)
Visit a parse tree produced by DMParser.value_range.
Result VisitTernery ([NotNull] DMParser.TerneryContext context)
Visit a parse tree produced by DMParser.ternery.
Result VisitLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Visit a parse tree produced by DMParser.lhrh_op.
Result VisitValue ([NotNull] DMParser.ValueContext context)
Visit a parse tree produced by DMParser.value.
Result VisitConstexpr ([NotNull] DMParser.ConstexprContext context)
Visit a parse tree produced by DMParser.constexpr.
Result VisitAssignment ([NotNull] DMParser.AssignmentContext context)
Visit a parse tree produced by DMParser.assignment.
Result VisitAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Visit a parse tree produced by DMParser.assignment_op.
Result VisitEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Visit a parse tree produced by DMParser.embedded_expression.
Result VisitInner_string ([NotNull] DMParser.Inner_stringContext context)
Visit a parse tree produced by DMParser.inner_string.
Result VisitInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Visit a parse tree produced by DMParser.inner_string_entry.
Result VisitString_entry ([NotNull] DMParser.String_entryContext context)
Visit a parse tree produced by DMParser.string_entry.
Result VisitFile_ref ([NotNull] DMParser.File_refContext context)
Visit a parse tree produced by DMParser.file_ref.
Result VisitNumber ([NotNull] DMParser.NumberContext context)
Visit a parse tree produced by DMParser.number.
Result VisitEquals ([NotNull] DMParser.EqualsContext context)
Visit a parse tree produced by DMParser.equals.
Result VisitNot_equals ([NotNull] DMParser.Not_equalsContext context)
Visit a parse tree produced by DMParser.not_equals.
Result VisitAnd ([NotNull] DMParser.AndContext context)
Visit a parse tree produced by DMParser.and.
Result VisitOr ([NotNull] DMParser.OrContext context)
Visit a parse tree produced by DMParser.or.
Result VisitOr_equals ([NotNull] DMParser.Or_equalsContext context)
Visit a parse tree produced by DMParser.or_equals.
Result VisitAnd_equals ([NotNull] DMParser.And_equalsContext context)
Visit a parse tree produced by DMParser.and_equals.
Result VisitXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Visit a parse tree produced by DMParser.xor_equals.
Result VisitMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Visit a parse tree produced by DMParser.mult_equals.
Result VisitMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Visit a parse tree produced by DMParser.minus_equals.
Result VisitPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Visit a parse tree produced by DMParser.plus_equals.
Result VisitSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Visit a parse tree produced by DMParser.slash_equals.
Result VisitRoot_type ([NotNull] DMParser.Root_typeContext context)
Visit a parse tree produced by DMParser.root_type.
Detailed Description
This interface defines a complete generic visitor for a parse tree produced by DMParser.
Template Parameters
Result The return type of the visit operation.
Definition at line 34 of file DMVisitor.cs.
Member Function Documentation
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAnd ([NotNull] DMParser.AndContext context)
Visit a parse tree produced by DMParser.and.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.AndContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAnd_equals ([NotNull] DMParser.And_equalsContext context)
Visit a parse tree produced by DMParser.and_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.And_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitArgument_decl ([NotNull] DMParser.Argument_declContext context)
Visit a parse tree produced by DMParser.argument_decl.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Argument_declContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitArgument_def ([NotNull] DMParser.Argument_defContext context)
Visit a parse tree produced by DMParser.argument_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Argument_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitArguments ([NotNull] DMParser.ArgumentsContext context)
Visit a parse tree produced by DMParser.arguments.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.ArgumentsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitArguments_def ([NotNull] DMParser.Arguments_defContext context)
Visit a parse tree produced by DMParser.arguments_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Arguments_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAssignment ([NotNull] DMParser.AssignmentContext context)
Visit a parse tree produced by DMParser.assignment.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.AssignmentContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAssignment_op ([NotNull] DMParser.Assignment_opContext context)
Visit a parse tree produced by DMParser.assignment_op.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Assignment_opContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAssignment_statement ([NotNull] DMParser.Assignment_statementContext context)
Visit a parse tree produced by DMParser.assignment_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Assignment_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAssociated_argument ([NotNull] DMParser.Associated_argumentContext context)
Visit a parse tree produced by DMParser.associated_argument.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Associated_argumentContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitAssociated_arguments ([NotNull] DMParser.Associated_argumentsContext context)
Visit a parse tree produced by DMParser.associated_arguments.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Associated_argumentsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitBlock ([NotNull] DMParser.BlockContext context)
Visit a parse tree produced by DMParser.block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.BlockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitConst_if_check ([NotNull] DMParser.Const_if_checkContext context)
Visit a parse tree produced by DMParser.const_if_check.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Const_if_checkContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitConstexpr ([NotNull] DMParser.ConstexprContext context)
Visit a parse tree produced by DMParser.constexpr.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.ConstexprContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitControl_flow ([NotNull] DMParser.Control_flowContext context)
Visit a parse tree produced by DMParser.control_flow.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Control_flowContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitCustom_id_typepath ([NotNull] DMParser.Custom_id_typepathContext context)
Visit a parse tree produced by DMParser.custom_id_typepath.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Custom_id_typepathContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitCustom_id_typepath_block ([NotNull] DMParser.Custom_id_typepath_blockContext context)
Visit a parse tree produced by DMParser.custom_id_typepath_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Custom_id_typepath_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDatum_access ([NotNull] DMParser.Datum_accessContext context)
Visit a parse tree produced by DMParser.datum_access.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Datum_accessContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDatum_def ([NotNull] DMParser.Datum_defContext context)
Visit a parse tree produced by DMParser.datum_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Datum_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDatum_def_block ([NotNull] DMParser.Datum_def_blockContext context)
Visit a parse tree produced by DMParser.datum_def_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Datum_def_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDatum_def_contents ([NotNull] DMParser.Datum_def_contentsContext context)
Visit a parse tree produced by DMParser.datum_def_contents.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Datum_def_contentsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDatum_inner_def ([NotNull] DMParser.Datum_inner_defContext context)
Visit a parse tree produced by DMParser.datum_inner_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Datum_inner_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitDefinition ([NotNull] DMParser.DefinitionContext context)
Visit a parse tree produced by DMParser.definition.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.DefinitionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitEmbedded_expression ([NotNull] DMParser.Embedded_expressionContext context)
Visit a parse tree produced by DMParser.embedded_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Embedded_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitEquals ([NotNull] DMParser.EqualsContext context)
Visit a parse tree produced by DMParser.equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.EqualsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitExpression ([NotNull] DMParser.ExpressionContext context)
Visit a parse tree produced by DMParser.expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.ExpressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFile_ref ([NotNull] DMParser.File_refContext context)
Visit a parse tree produced by DMParser.file_ref.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.File_refContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFor_expression ([NotNull] DMParser.For_expressionContext context)
Visit a parse tree produced by DMParser.for_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.For_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFor_in ([NotNull] DMParser.For_inContext context)
Visit a parse tree produced by DMParser.for_in.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.For_inContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFor_optional_argument_def ([NotNull] DMParser.For_optional_argument_defContext context)
Visit a parse tree produced by DMParser.for_optional_argument_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.For_optional_argument_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFor_standard ([NotNull] DMParser.For_standardContext context)
Visit a parse tree produced by DMParser.for_standard.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.For_standardContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFor_statement ([NotNull] DMParser.For_statementContext context)
Visit a parse tree produced by DMParser.for_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.For_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitFull_typepath ([NotNull] DMParser.Full_typepathContext context)
Visit a parse tree produced by DMParser.full_typepath.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Full_typepathContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_and_assignment ([NotNull] DMParser.Id_and_assignmentContext context)
Visit a parse tree produced by DMParser.id_and_assignment.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_and_assignmentContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_specifier ([NotNull] DMParser.Id_specifierContext context)
Visit a parse tree produced by DMParser.id_specifier.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_specifierContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_typepath ([NotNull] DMParser.Id_typepathContext context)
Visit a parse tree produced by DMParser.id_typepath.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_typepathContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_typepath_block ([NotNull] DMParser.Id_typepath_blockContext context)
Visit a parse tree produced by DMParser.id_typepath_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_typepath_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_typepath_decl ([NotNull] DMParser.Id_typepath_declContext context)
Visit a parse tree produced by DMParser.id_typepath_decl.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_typepath_declContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_typepath_decl_block ([NotNull] DMParser.Id_typepath_decl_blockContext context)
Visit a parse tree produced by DMParser.id_typepath_decl_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_typepath_decl_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitId_typepath_oneline ([NotNull] DMParser.Id_typepath_onelineContext context)
Visit a parse tree produced by DMParser.id_typepath_oneline.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Id_typepath_onelineContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitIf_check ([NotNull] DMParser.If_checkContext context)
Visit a parse tree produced by DMParser.if_check.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.If_checkContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitIf_continuation ([NotNull] DMParser.If_continuationContext context)
Visit a parse tree produced by DMParser.if_continuation.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.If_continuationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitIf_statement ([NotNull] DMParser.If_statementContext context)
Visit a parse tree produced by DMParser.if_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.If_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitInner_expression ([NotNull] DMParser.Inner_expressionContext context)
Visit a parse tree produced by DMParser.inner_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Inner_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitInner_string ([NotNull] DMParser.Inner_stringContext context)
Visit a parse tree produced by DMParser.inner_string.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Inner_stringContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitInner_string_entry ([NotNull] DMParser.Inner_string_entryContext context)
Visit a parse tree produced by DMParser.inner_string_entry.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Inner_string_entryContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitLanguage ([NotNull] DMParser.LanguageContext context)
Visit a parse tree produced by DMParser.language.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.LanguageContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitLhrh_op ([NotNull] DMParser.Lhrh_opContext context)
Visit a parse tree produced by DMParser.lhrh_op.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Lhrh_opContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitList_declaration ([NotNull] DMParser.List_declarationContext context)
Visit a parse tree produced by DMParser.list_declaration.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.List_declarationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitMinus_equals ([NotNull] DMParser.Minus_equalsContext context)
Visit a parse tree produced by DMParser.minus_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Minus_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitMult_equals ([NotNull] DMParser.Mult_equalsContext context)
Visit a parse tree produced by DMParser.mult_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Mult_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitNon_recursive_expression ([NotNull] DMParser.Non_recursive_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Non_recursive_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitNon_recursive_inner_expression ([NotNull] DMParser.Non_recursive_inner_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_inner_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Non_recursive_inner_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitNon_recursive_wrapped_expression ([NotNull] DMParser.Non_recursive_wrapped_expressionContext context)
Visit a parse tree produced by DMParser.non_recursive_wrapped_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Non_recursive_wrapped_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitNot_equals ([NotNull] DMParser.Not_equalsContext context)
Visit a parse tree produced by DMParser.not_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Not_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitNumber ([NotNull] DMParser.NumberContext context)
Visit a parse tree produced by DMParser.number.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.NumberContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitOperation ([NotNull] DMParser.OperationContext context)
Visit a parse tree produced by DMParser.operation.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.OperationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitOptional_expression ([NotNull] DMParser.Optional_expressionContext context)
Visit a parse tree produced by DMParser.optional_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Optional_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitOptional_slash ([NotNull] DMParser.Optional_slashContext context)
Visit a parse tree produced by DMParser.optional_slash.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Optional_slashContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitOr ([NotNull] DMParser.OrContext context)
Visit a parse tree produced by DMParser.or.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.OrContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitOr_equals ([NotNull] DMParser.Or_equalsContext context)
Visit a parse tree produced by DMParser.or_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Or_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitPlus_equals ([NotNull] DMParser.Plus_equalsContext context)
Visit a parse tree produced by DMParser.plus_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Plus_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProc_def ([NotNull] DMParser.Proc_defContext context)
Visit a parse tree produced by DMParser.proc_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Proc_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProc_id_def ([NotNull] DMParser.Proc_id_defContext context)
Visit a parse tree produced by DMParser.proc_id_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Proc_id_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProc_id_def_block ([NotNull] DMParser.Proc_id_def_blockContext context)
Visit a parse tree produced by DMParser.proc_id_def_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Proc_id_def_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProc_invocation ([NotNull] DMParser.Proc_invocationContext context)
Visit a parse tree produced by DMParser.proc_invocation.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Proc_invocationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProccall ([NotNull] DMParser.ProccallContext context)
Visit a parse tree produced by DMParser.proccall.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.ProccallContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitProccall_statement ([NotNull] DMParser.Proccall_statementContext context)
Visit a parse tree produced by DMParser.proccall_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Proccall_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitRoot_if_continuation ([NotNull] DMParser.Root_if_continuationContext context)
Visit a parse tree produced by DMParser.root_if_continuation.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Root_if_continuationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitRoot_switch_block ([NotNull] DMParser.Root_switch_blockContext context)
Visit a parse tree produced by DMParser.root_switch_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Root_switch_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitRoot_type ([NotNull] DMParser.Root_typeContext context)
Visit a parse tree produced by DMParser.root_type.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Root_typeContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitRoot_var_def ([NotNull] DMParser.Root_var_defContext context)
Visit a parse tree produced by DMParser.root_var_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Root_var_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitSlash_equals ([NotNull] DMParser.Slash_equalsContext context)
Visit a parse tree produced by DMParser.slash_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Slash_equalsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitSpawn_invocation ([NotNull] DMParser.Spawn_invocationContext context)
Visit a parse tree produced by DMParser.spawn_invocation.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Spawn_invocationContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitSpawn_statement ([NotNull] DMParser.Spawn_statementContext context)
Visit a parse tree produced by DMParser.spawn_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Spawn_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitStatement ([NotNull] DMParser.StatementContext context)
Visit a parse tree produced by DMParser.statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.StatementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitStatements ([NotNull] DMParser.StatementsContext context)
Visit a parse tree produced by DMParser.statements.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.StatementsContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitStatic_or_global ([NotNull] DMParser.Static_or_globalContext context)
Visit a parse tree produced by DMParser.static_or_global.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Static_or_globalContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitString_entry ([NotNull] DMParser.String_entryContext context)
Visit a parse tree produced by DMParser.string_entry.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.String_entryContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitString_text ([NotNull] DMParser.String_textContext context)
Visit a parse tree produced by DMParser.string_text.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.String_textContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitSwitch_block ([NotNull] DMParser.Switch_blockContext context)
Visit a parse tree produced by DMParser.switch_block.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Switch_blockContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitSwitch_statement ([NotNull] DMParser.Switch_statementContext context)
Visit a parse tree produced by DMParser.switch_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Switch_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitTernery ([NotNull] DMParser.TerneryContext context)
Visit a parse tree produced by DMParser.ternery.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.TerneryContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitTypepath ([NotNull] DMParser.TypepathContext context)
Visit a parse tree produced by DMParser.typepath.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.TypepathContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitUnquotable_associated_argument ([NotNull] DMParser.Unquotable_associated_argumentContext context)
Visit a parse tree produced by DMParser.unquotable_associated_argument.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Unquotable_associated_argumentContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitValue ([NotNull] DMParser.ValueContext context)
Visit a parse tree produced by DMParser.value.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.ValueContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitValue_range ([NotNull] DMParser.Value_rangeContext context)
Visit a parse tree produced by DMParser.value_range.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Value_rangeContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitVar_def ([NotNull] DMParser.Var_defContext context)
Visit a parse tree produced by DMParser.var_def.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Var_defContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitWhile_statement ([NotNull] DMParser.While_statementContext context)
Visit a parse tree produced by DMParser.while_statement.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.While_statementContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitWrapped_expression ([NotNull] DMParser.Wrapped_expressionContext context)
Visit a parse tree produced by DMParser.wrapped_expression.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Wrapped_expressionContext.Accept< TResult >().
Result Dangl.Calculator.Generated.IDMVisitor< Result >.VisitXor_equals ([NotNull] DMParser.Xor_equalsContext context)
Visit a parse tree produced by DMParser.xor_equals.
Parameters
context The parse tree.
<return>The visitor result.</return>
Implemented in Dangl.Calculator.Generated.DMBaseVisitor< Result >.
Referenced by Dangl.Calculator.Generated.DMParser.Xor_equalsContext.Accept< TResult >().
The documentation for this interface was generated from the following file:
DMLang.Server/obj/Release/DMVisitor.cs