dm-langserver: DMLang.Server.Parser.IPreprocessorListener Interface Reference
DMLang.Server.Parser.IPreprocessorListener Interface Reference
This interface defines a complete listener for a parse tree produced by PreprocessorParser.
Public Member Functions
void EnterLanguage ([NotNull] PreprocessorParser.LanguageContext context)
Enter a parse tree produced by PreprocessorParser.language.
void ExitLanguage ([NotNull] PreprocessorParser.LanguageContext context)
Exit a parse tree produced by PreprocessorParser.language.
void EnterDeclaration ([NotNull] PreprocessorParser.DeclarationContext context)
Enter a parse tree produced by PreprocessorParser.declaration.
void ExitDeclaration ([NotNull] PreprocessorParser.DeclarationContext context)
Exit a parse tree produced by PreprocessorParser.declaration.
void EnterStatement ([NotNull] PreprocessorParser.StatementContext context)
Enter a parse tree produced by PreprocessorParser.statement.
void ExitStatement ([NotNull] PreprocessorParser.StatementContext context)
Exit a parse tree produced by PreprocessorParser.statement.
void EnterDoc_comment ([NotNull] PreprocessorParser.Doc_commentContext context)
Enter a parse tree produced by PreprocessorParser.doc_comment.
void ExitDoc_comment ([NotNull] PreprocessorParser.Doc_commentContext context)
Exit a parse tree produced by PreprocessorParser.doc_comment.
void EnterUndef_statement ([NotNull] PreprocessorParser.Undef_statementContext context)
Enter a parse tree produced by PreprocessorParser.undef_statement.
void ExitUndef_statement ([NotNull] PreprocessorParser.Undef_statementContext context)
Exit a parse tree produced by PreprocessorParser.undef_statement.
void EnterWarning_statement ([NotNull] PreprocessorParser.Warning_statementContext context)
Enter a parse tree produced by PreprocessorParser.warning_statement.
void ExitWarning_statement ([NotNull] PreprocessorParser.Warning_statementContext context)
Exit a parse tree produced by PreprocessorParser.warning_statement.
void EnterError_statement ([NotNull] PreprocessorParser.Error_statementContext context)
Enter a parse tree produced by PreprocessorParser.error_statement.
void ExitError_statement ([NotNull] PreprocessorParser.Error_statementContext context)
Exit a parse tree produced by PreprocessorParser.error_statement.
void EnterText ([NotNull] PreprocessorParser.TextContext context)
Enter a parse tree produced by PreprocessorParser.text.
void ExitText ([NotNull] PreprocessorParser.TextContext context)
Exit a parse tree produced by PreprocessorParser.text.
void EnterIf_statement ([NotNull] PreprocessorParser.If_statementContext context)
Enter a parse tree produced by PreprocessorParser.if_statement.
void ExitIf_statement ([NotNull] PreprocessorParser.If_statementContext context)
Exit a parse tree produced by PreprocessorParser.if_statement.
void EnterIf_start ([NotNull] PreprocessorParser.If_startContext context)
Enter a parse tree produced by PreprocessorParser.if_start.
void ExitIf_start ([NotNull] PreprocessorParser.If_startContext context)
Exit a parse tree produced by PreprocessorParser.if_start.
void EnterIf_condition ([NotNull] PreprocessorParser.If_conditionContext context)
Enter a parse tree produced by PreprocessorParser.if_condition.
void ExitIf_condition ([NotNull] PreprocessorParser.If_conditionContext context)
Exit a parse tree produced by PreprocessorParser.if_condition.
void EnterNon_recursive_if_condition ([NotNull] PreprocessorParser.Non_recursive_if_conditionContext context)
Enter a parse tree produced by PreprocessorParser.non_recursive_if_condition.
void ExitNon_recursive_if_condition ([NotNull] PreprocessorParser.Non_recursive_if_conditionContext context)
Exit a parse tree produced by PreprocessorParser.non_recursive_if_condition.
void EnterIf_continuation ([NotNull] PreprocessorParser.If_continuationContext context)
Enter a parse tree produced by PreprocessorParser.if_continuation.
void ExitIf_continuation ([NotNull] PreprocessorParser.If_continuationContext context)
Exit a parse tree produced by PreprocessorParser.if_continuation.
void EnterIf_closure ([NotNull] PreprocessorParser.If_closureContext context)
Enter a parse tree produced by PreprocessorParser.if_closure.
void ExitIf_closure ([NotNull] PreprocessorParser.If_closureContext context)
Exit a parse tree produced by PreprocessorParser.if_closure.
void EnterLhrh_op ([NotNull] PreprocessorParser.Lhrh_opContext context)
Enter a parse tree produced by PreprocessorParser.lhrh_op.
void ExitLhrh_op ([NotNull] PreprocessorParser.Lhrh_opContext context)
Exit a parse tree produced by PreprocessorParser.lhrh_op.
void EnterEquals ([NotNull] PreprocessorParser.EqualsContext context)
Enter a parse tree produced by PreprocessorParser.equals.
void ExitEquals ([NotNull] PreprocessorParser.EqualsContext context)
Exit a parse tree produced by PreprocessorParser.equals.
void EnterNot_equals ([NotNull] PreprocessorParser.Not_equalsContext context)
Enter a parse tree produced by PreprocessorParser.not_equals.
void ExitNot_equals ([NotNull] PreprocessorParser.Not_equalsContext context)
Exit a parse tree produced by PreprocessorParser.not_equals.
void EnterAnd ([NotNull] PreprocessorParser.AndContext context)
Enter a parse tree produced by PreprocessorParser.and.
void ExitAnd ([NotNull] PreprocessorParser.AndContext context)
Exit a parse tree produced by PreprocessorParser.and.
void EnterOr ([NotNull] PreprocessorParser.OrContext context)
Enter a parse tree produced by PreprocessorParser.or.
void ExitOr ([NotNull] PreprocessorParser.OrContext context)
Exit a parse tree produced by PreprocessorParser.or.
void EnterPow ([NotNull] PreprocessorParser.PowContext context)
Enter a parse tree produced by PreprocessorParser.pow.
void ExitPow ([NotNull] PreprocessorParser.PowContext context)
Exit a parse tree produced by PreprocessorParser.pow.
void EnterInclude_statement ([NotNull] PreprocessorParser.Include_statementContext context)
Enter a parse tree produced by PreprocessorParser.include_statement.
void ExitInclude_statement ([NotNull] PreprocessorParser.Include_statementContext context)
Exit a parse tree produced by PreprocessorParser.include_statement.
void EnterDefine_statement ([NotNull] PreprocessorParser.Define_statementContext context)
Enter a parse tree produced by PreprocessorParser.define_statement.
void ExitDefine_statement ([NotNull] PreprocessorParser.Define_statementContext context)
Exit a parse tree produced by PreprocessorParser.define_statement.
void EnterDefine ([NotNull] PreprocessorParser.DefineContext context)
Enter a parse tree produced by PreprocessorParser.define.
void ExitDefine ([NotNull] PreprocessorParser.DefineContext context)
Exit a parse tree produced by PreprocessorParser.define.
void EnterArguments ([NotNull] PreprocessorParser.ArgumentsContext context)
Enter a parse tree produced by PreprocessorParser.arguments.
void ExitArguments ([NotNull] PreprocessorParser.ArgumentsContext context)
Exit a parse tree produced by PreprocessorParser.arguments.
void EnterArgument_list ([NotNull] PreprocessorParser.Argument_listContext context)
Enter a parse tree produced by PreprocessorParser.argument_list.
void ExitArgument_list ([NotNull] PreprocessorParser.Argument_listContext context)
Exit a parse tree produced by PreprocessorParser.argument_list.
void EnterMacro ([NotNull] PreprocessorParser.MacroContext context)
Enter a parse tree produced by PreprocessorParser.macro.
void ExitMacro ([NotNull] PreprocessorParser.MacroContext context)
Exit a parse tree produced by PreprocessorParser.macro.
void EnterMacro_line ([NotNull] PreprocessorParser.Macro_lineContext context)
Enter a parse tree produced by PreprocessorParser.macro_line.
void ExitMacro_line ([NotNull] PreprocessorParser.Macro_lineContext context)
Exit a parse tree produced by PreprocessorParser.macro_line.
void EnterMacro_content ([NotNull] PreprocessorParser.Macro_contentContext context)
Enter a parse tree produced by PreprocessorParser.macro_content.
void ExitMacro_content ([NotNull] PreprocessorParser.Macro_contentContext context)
Exit a parse tree produced by PreprocessorParser.macro_content.
void EnterExplicit_replacement ([NotNull] PreprocessorParser.Explicit_replacementContext context)
Enter a parse tree produced by PreprocessorParser.explicit_replacement.
void ExitExplicit_replacement ([NotNull] PreprocessorParser.Explicit_replacementContext context)
Exit a parse tree produced by PreprocessorParser.explicit_replacement.
void EnterStringified_replacement ([NotNull] PreprocessorParser.Stringified_replacementContext context)
Enter a parse tree produced by PreprocessorParser.stringified_replacement.
void ExitStringified_replacement ([NotNull] PreprocessorParser.Stringified_replacementContext context)
Exit a parse tree produced by PreprocessorParser.stringified_replacement.
Detailed Description
This interface defines a complete listener for a parse tree produced by PreprocessorParser.
Definition at line 33 of file PreprocessorListener.cs.
Member Function Documentation
void DMLang.Server.Parser.IPreprocessorListener.EnterAnd ([NotNull] PreprocessorParser.AndContext context)
Enter a parse tree produced by PreprocessorParser.and.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.AndContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterArgument_list ([NotNull] PreprocessorParser.Argument_listContext context)
Enter a parse tree produced by PreprocessorParser.argument_list.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Argument_listContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterArguments ([NotNull] PreprocessorParser.ArgumentsContext context)
Enter a parse tree produced by PreprocessorParser.arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.ArgumentsContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterDeclaration ([NotNull] PreprocessorParser.DeclarationContext context)
Enter a parse tree produced by PreprocessorParser.declaration.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.DeclarationContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterDefine ([NotNull] PreprocessorParser.DefineContext context)
Enter a parse tree produced by PreprocessorParser.define.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.DefineContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterDefine_statement ([NotNull] PreprocessorParser.Define_statementContext context)
Enter a parse tree produced by PreprocessorParser.define_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Define_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterDoc_comment ([NotNull] PreprocessorParser.Doc_commentContext context)
Enter a parse tree produced by PreprocessorParser.doc_comment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Doc_commentContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterEquals ([NotNull] PreprocessorParser.EqualsContext context)
Enter a parse tree produced by PreprocessorParser.equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.EqualsContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterError_statement ([NotNull] PreprocessorParser.Error_statementContext context)
Enter a parse tree produced by PreprocessorParser.error_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Error_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterExplicit_replacement ([NotNull] PreprocessorParser.Explicit_replacementContext context)
Enter a parse tree produced by PreprocessorParser.explicit_replacement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Explicit_replacementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterIf_closure ([NotNull] PreprocessorParser.If_closureContext context)
Enter a parse tree produced by PreprocessorParser.if_closure.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_closureContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterIf_condition ([NotNull] PreprocessorParser.If_conditionContext context)
Enter a parse tree produced by PreprocessorParser.if_condition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_conditionContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterIf_continuation ([NotNull] PreprocessorParser.If_continuationContext context)
Enter a parse tree produced by PreprocessorParser.if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_continuationContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterIf_start ([NotNull] PreprocessorParser.If_startContext context)
Enter a parse tree produced by PreprocessorParser.if_start.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_startContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterIf_statement ([NotNull] PreprocessorParser.If_statementContext context)
Enter a parse tree produced by PreprocessorParser.if_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterInclude_statement ([NotNull] PreprocessorParser.Include_statementContext context)
Enter a parse tree produced by PreprocessorParser.include_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Include_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterLanguage ([NotNull] PreprocessorParser.LanguageContext context)
Enter a parse tree produced by PreprocessorParser.language.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.LanguageContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterLhrh_op ([NotNull] PreprocessorParser.Lhrh_opContext context)
Enter a parse tree produced by PreprocessorParser.lhrh_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Lhrh_opContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterMacro ([NotNull] PreprocessorParser.MacroContext context)
Enter a parse tree produced by PreprocessorParser.macro.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.MacroContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterMacro_content ([NotNull] PreprocessorParser.Macro_contentContext context)
Enter a parse tree produced by PreprocessorParser.macro_content.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Macro_contentContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterMacro_line ([NotNull] PreprocessorParser.Macro_lineContext context)
Enter a parse tree produced by PreprocessorParser.macro_line.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Macro_lineContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterNon_recursive_if_condition ([NotNull] PreprocessorParser.Non_recursive_if_conditionContext context)
Enter a parse tree produced by PreprocessorParser.non_recursive_if_condition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Non_recursive_if_conditionContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterNot_equals ([NotNull] PreprocessorParser.Not_equalsContext context)
Enter a parse tree produced by PreprocessorParser.not_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Not_equalsContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterOr ([NotNull] PreprocessorParser.OrContext context)
Enter a parse tree produced by PreprocessorParser.or.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.OrContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterPow ([NotNull] PreprocessorParser.PowContext context)
Enter a parse tree produced by PreprocessorParser.pow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.PowContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterStatement ([NotNull] PreprocessorParser.StatementContext context)
Enter a parse tree produced by PreprocessorParser.statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.StatementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterStringified_replacement ([NotNull] PreprocessorParser.Stringified_replacementContext context)
Enter a parse tree produced by PreprocessorParser.stringified_replacement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Stringified_replacementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterText ([NotNull] PreprocessorParser.TextContext context)
Enter a parse tree produced by PreprocessorParser.text.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.TextContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterUndef_statement ([NotNull] PreprocessorParser.Undef_statementContext context)
Enter a parse tree produced by PreprocessorParser.undef_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Undef_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.EnterWarning_statement ([NotNull] PreprocessorParser.Warning_statementContext context)
Enter a parse tree produced by PreprocessorParser.warning_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Warning_statementContext.EnterRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitAnd ([NotNull] PreprocessorParser.AndContext context)
Exit a parse tree produced by PreprocessorParser.and.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.AndContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitArgument_list ([NotNull] PreprocessorParser.Argument_listContext context)
Exit a parse tree produced by PreprocessorParser.argument_list.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Argument_listContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitArguments ([NotNull] PreprocessorParser.ArgumentsContext context)
Exit a parse tree produced by PreprocessorParser.arguments.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.ArgumentsContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitDeclaration ([NotNull] PreprocessorParser.DeclarationContext context)
Exit a parse tree produced by PreprocessorParser.declaration.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.DeclarationContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitDefine ([NotNull] PreprocessorParser.DefineContext context)
Exit a parse tree produced by PreprocessorParser.define.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.DefineContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitDefine_statement ([NotNull] PreprocessorParser.Define_statementContext context)
Exit a parse tree produced by PreprocessorParser.define_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Define_statementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitDoc_comment ([NotNull] PreprocessorParser.Doc_commentContext context)
Exit a parse tree produced by PreprocessorParser.doc_comment.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Doc_commentContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitEquals ([NotNull] PreprocessorParser.EqualsContext context)
Exit a parse tree produced by PreprocessorParser.equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.EqualsContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitError_statement ([NotNull] PreprocessorParser.Error_statementContext context)
Exit a parse tree produced by PreprocessorParser.error_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Error_statementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitExplicit_replacement ([NotNull] PreprocessorParser.Explicit_replacementContext context)
Exit a parse tree produced by PreprocessorParser.explicit_replacement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Explicit_replacementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitIf_closure ([NotNull] PreprocessorParser.If_closureContext context)
Exit a parse tree produced by PreprocessorParser.if_closure.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_closureContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitIf_condition ([NotNull] PreprocessorParser.If_conditionContext context)
Exit a parse tree produced by PreprocessorParser.if_condition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_conditionContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitIf_continuation ([NotNull] PreprocessorParser.If_continuationContext context)
Exit a parse tree produced by PreprocessorParser.if_continuation.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_continuationContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitIf_start ([NotNull] PreprocessorParser.If_startContext context)
Exit a parse tree produced by PreprocessorParser.if_start.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_startContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitIf_statement ([NotNull] PreprocessorParser.If_statementContext context)
Exit a parse tree produced by PreprocessorParser.if_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.If_statementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitInclude_statement ([NotNull] PreprocessorParser.Include_statementContext context)
Exit a parse tree produced by PreprocessorParser.include_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Include_statementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitLanguage ([NotNull] PreprocessorParser.LanguageContext context)
Exit a parse tree produced by PreprocessorParser.language.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.LanguageContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitLhrh_op ([NotNull] PreprocessorParser.Lhrh_opContext context)
Exit a parse tree produced by PreprocessorParser.lhrh_op.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Lhrh_opContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitMacro ([NotNull] PreprocessorParser.MacroContext context)
Exit a parse tree produced by PreprocessorParser.macro.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.MacroContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitMacro_content ([NotNull] PreprocessorParser.Macro_contentContext context)
Exit a parse tree produced by PreprocessorParser.macro_content.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Macro_contentContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitMacro_line ([NotNull] PreprocessorParser.Macro_lineContext context)
Exit a parse tree produced by PreprocessorParser.macro_line.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Macro_lineContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitNon_recursive_if_condition ([NotNull] PreprocessorParser.Non_recursive_if_conditionContext context)
Exit a parse tree produced by PreprocessorParser.non_recursive_if_condition.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Non_recursive_if_conditionContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitNot_equals ([NotNull] PreprocessorParser.Not_equalsContext context)
Exit a parse tree produced by PreprocessorParser.not_equals.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Not_equalsContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitOr ([NotNull] PreprocessorParser.OrContext context)
Exit a parse tree produced by PreprocessorParser.or.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.OrContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitPow ([NotNull] PreprocessorParser.PowContext context)
Exit a parse tree produced by PreprocessorParser.pow.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.PowContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitStatement ([NotNull] PreprocessorParser.StatementContext context)
Exit a parse tree produced by PreprocessorParser.statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.StatementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitStringified_replacement ([NotNull] PreprocessorParser.Stringified_replacementContext context)
Exit a parse tree produced by PreprocessorParser.stringified_replacement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Stringified_replacementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitText ([NotNull] PreprocessorParser.TextContext context)
Exit a parse tree produced by PreprocessorParser.text.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.TextContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitUndef_statement ([NotNull] PreprocessorParser.Undef_statementContext context)
Exit a parse tree produced by PreprocessorParser.undef_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Undef_statementContext.ExitRule().
void DMLang.Server.Parser.IPreprocessorListener.ExitWarning_statement ([NotNull] PreprocessorParser.Warning_statementContext context)
Exit a parse tree produced by PreprocessorParser.warning_statement.
Parameters
context The parse tree.
Implemented in DMLang.Server.Parser.PreprocessorBaseListener.
Referenced by DMLang.Server.Parser.PreprocessorParser.Warning_statementContext.ExitRule().
The documentation for this interface was generated from the following file:
DMLang.Server/obj/Release/PreprocessorListener.cs